import { NextResponse, type NextRequest } from "next/server";
import { db } from "@/lib/db";

/**
 * One-shot Relationship Intelligence Engine schema delta for PRODUCTION:
 * adds new columns to bisneys_people / bisneys_relationships /
 * bisneys_relationship_types and creates bisneys_employments +
 * bisneys_relationship_suggestions. Token-gated, idempotent. Remove after use.
 */
export const dynamic = "force-dynamic";
export const maxDuration = 60;

const DDL_B64 = [
  "QUxURVIgVEFCTEUgImJpc25leXNfcGVvcGxlIiBBREQgQ09MVU1OICAgICAiYXZhdGFyVXJsIiBURVhULApBREQgQ09MVU1OICAgICAiaGVhZGxpbmUiIFRF",
  "WFQsCkFERCBDT0xVTU4gICAgICJpc1ZlcmlmaWVkIiBCT09MRUFOIE5PVCBOVUxMIERFRkFVTFQgZmFsc2UsCkFERCBDT0xVTU4gICAgICJsYXN0QWN0aXZp",
  "dHlBdCIgVElNRVNUQU1QKDMpLApBREQgQ09MVU1OICAgICAibGlua2VkaW5VcmwiIFRFWFQsCkFERCBDT0xVTU4gICAgICJuZXR3b3JrU2NvcmUiIElOVEVH",
  "RVIsCkFERCBDT0xVTU4gICAgICJyZWZlcnJhbFNjb3JlIiBJTlRFR0VSLApBREQgQ09MVU1OICAgICAic2Vjb25kYXJ5RW1haWwiIFRFWFQsCkFERCBDT0xV",
  "TU4gICAgICJzZWNvbmRhcnlQaG9uZSIgVEVYVCwKQUREIENPTFVNTiAgICAgInVwZGF0ZWRCeUlkIiBURVhULApBREQgQ09MVU1OICAgICAidmVyaWZpY2F0",
  "aW9uU3RhdHVzIiBURVhUIERFRkFVTFQgJ1VOVkVSSUZJRUQnOwoKQUxURVIgVEFCTEUgImJpc25leXNfcmVsYXRpb25zaGlwX3R5cGVzIiBBREQgQ09MVU1O",
  "ICAgICAiY29sb3IiIFRFWFQsCkFERCBDT0xVTU4gICAgICJkZXNjcmlwdGlvbiIgVEVYVCwKQUREIENPTFVNTiAgICAgImRpcmVjdGVkIiBCT09MRUFOIE5P",
  "VCBOVUxMIERFRkFVTFQgdHJ1ZSwKQUREIENPTFVNTiAgICAgImljb24iIFRFWFQsCkFERCBDT0xVTU4gICAgICJpc0FjdGl2ZSIgQk9PTEVBTiBOT1QgTlVM",
  "TCBERUZBVUxUIHRydWUsCkFERCBDT0xVTU4gICAgICJzbHVnIiBURVhUOwoKQUxURVIgVEFCTEUgImJpc25leXNfcmVsYXRpb25zaGlwcyIgQUREIENPTFVN",
  "TiAgICAgImNvbmZpZGVuY2VTY29yZSIgSU5URUdFUiwKQUREIENPTFVNTiAgICAgImRlbGV0ZWRBdCIgVElNRVNUQU1QKDMpLApBREQgQ09MVU1OICAgICAi",
  "ZGVsZXRlZEJ5SWQiIFRFWFQsCkFERCBDT0xVTU4gICAgICJzb3VyY2VUeXBlIiBURVhULApBREQgQ09MVU1OICAgICAic3RyZW5ndGhTY29yZSIgSU5URUdF",
  "UiwKQUREIENPTFVNTiAgICAgInVwZGF0ZWRBdCIgVElNRVNUQU1QKDMpIE5PVCBOVUxMIERFRkFVTFQgQ1VSUkVOVF9USU1FU1RBTVA7CgpDUkVBVEUgVEFC",
  "TEUgImJpc25leXNfZW1wbG95bWVudHMiICgKICAgICJpZCIgVEVYVCBOT1QgTlVMTCwKICAgICJwZXJzb25JZCIgVEVYVCBOT1QgTlVMTCwKICAgICJjb21w",
  "YW55SWQiIFRFWFQsCiAgICAiY29tcGFueU5hbWUiIFRFWFQsCiAgICAidGl0bGUiIFRFWFQsCiAgICAiZGVwYXJ0bWVudCIgVEVYVCwKICAgICJzdGFydERh",
  "dGUiIFRJTUVTVEFNUCgzKSwKICAgICJlbmREYXRlIiBUSU1FU1RBTVAoMyksCiAgICAiaXNDdXJyZW50IiBCT09MRUFOIE5PVCBOVUxMIERFRkFVTFQgZmFs",
  "c2UsCiAgICAic291cmNlIiBURVhULAogICAgImNvbmZpcm1lZCIgQk9PTEVBTiBOT1QgTlVMTCBERUZBVUxUIGZhbHNlLAogICAgIm5vdGUiIFRFWFQsCiAg",
  "ICAiY3JlYXRlZEJ5SWQiIFRFWFQsCiAgICAiZGVsZXRlZEF0IiBUSU1FU1RBTVAoMyksCiAgICAiY3JlYXRlZEF0IiBUSU1FU1RBTVAoMykgTk9UIE5VTEwg",
  "REVGQVVMVCBDVVJSRU5UX1RJTUVTVEFNUCwKICAgICJ1cGRhdGVkQXQiIFRJTUVTVEFNUCgzKSBOT1QgTlVMTCwKCiAgICBDT05TVFJBSU5UICJiaXNuZXlz",
  "X2VtcGxveW1lbnRzX3BrZXkiIFBSSU1BUlkgS0VZICgiaWQiKQopOwoKQ1JFQVRFIFRBQkxFICJiaXNuZXlzX3JlbGF0aW9uc2hpcF9zdWdnZXN0aW9ucyIg",
  "KAogICAgImlkIiBURVhUIE5PVCBOVUxMLAogICAgInNvdXJjZVBlcnNvbklkIiBURVhUIE5PVCBOVUxMLAogICAgInRhcmdldFBlcnNvbklkIiBURVhUIE5P",
  "VCBOVUxMLAogICAgInN1Z2dlc3RlZFR5cGUiIFRFWFQsCiAgICAic2lnbmFsVHlwZSIgVEVYVCBOT1QgTlVMTCwKICAgICJyZWFzb24iIFRFWFQgTk9UIE5V",
  "TEwsCiAgICAiY29uZmlkZW5jZSIgVEVYVCBOT1QgTlVMTCBERUZBVUxUICdNRURJVU0nLAogICAgImNvbXBhbnlJZCIgVEVYVCwKICAgICJzdGF0dXMiIFRF",
  "WFQgTk9UIE5VTEwgREVGQVVMVCAnUEVORElORycsCiAgICAicmVzb2x2ZWRCeUlkIiBURVhULAogICAgInJlc29sdmVkQXQiIFRJTUVTVEFNUCgzKSwKICAg",
  "ICJjcmVhdGVkQXQiIFRJTUVTVEFNUCgzKSBOT1QgTlVMTCBERUZBVUxUIENVUlJFTlRfVElNRVNUQU1QLAoKICAgIENPTlNUUkFJTlQgImJpc25leXNfcmVs",
  "YXRpb25zaGlwX3N1Z2dlc3Rpb25zX3BrZXkiIFBSSU1BUlkgS0VZICgiaWQiKQopOwoKQ1JFQVRFIElOREVYICJiaXNuZXlzX2VtcGxveW1lbnRzX3BlcnNv",
  "bklkX2lkeCIgT04gImJpc25leXNfZW1wbG95bWVudHMiKCJwZXJzb25JZCIpOwoKQ1JFQVRFIElOREVYICJiaXNuZXlzX2VtcGxveW1lbnRzX2NvbXBhbnlJ",
  "ZF9pZHgiIE9OICJiaXNuZXlzX2VtcGxveW1lbnRzIigiY29tcGFueUlkIik7CgpDUkVBVEUgSU5ERVggImJpc25leXNfcmVsYXRpb25zaGlwX3N1Z2dlc3Rp",
  "b25zX3N0YXR1c19pZHgiIE9OICJiaXNuZXlzX3JlbGF0aW9uc2hpcF9zdWdnZXN0aW9ucyIoInN0YXR1cyIpOwoKQ1JFQVRFIFVOSVFVRSBJTkRFWCAiYmlz",
  "bmV5c19yZWxhdGlvbnNoaXBfc3VnZ2VzdGlvbnNfc291cmNlUGVyc29uSWRfdGFyZ2V0UGVyc29fa2V5IiBPTiAiYmlzbmV5c19yZWxhdGlvbnNoaXBfc3Vn",
  "Z2VzdGlvbnMiKCJzb3VyY2VQZXJzb25JZCIsICJ0YXJnZXRQZXJzb25JZCIsICJzaWduYWxUeXBlIik7CgpDUkVBVEUgSU5ERVggImJpc25leXNfcGVvcGxl",
  "X2xpbmtlZGluVXJsX2lkeCIgT04gImJpc25leXNfcGVvcGxlIigibGlua2VkaW5VcmwiKTsKCkNSRUFURSBVTklRVUUgSU5ERVggImJpc25leXNfcmVsYXRp",
  "b25zaGlwX3R5cGVzX3NsdWdfa2V5IiBPTiAiYmlzbmV5c19yZWxhdGlvbnNoaXBfdHlwZXMiKCJzbHVnIik7CgpDUkVBVEUgSU5ERVggImJpc25leXNfcmVs",
  "YXRpb25zaGlwc19jb21wYW55SWRfaWR4IiBPTiAiYmlzbmV5c19yZWxhdGlvbnNoaXBzIigiY29tcGFueUlkIik7CgpBTFRFUiBUQUJMRSAiYmlzbmV5c19l",
  "bXBsb3ltZW50cyIgQUREIENPTlNUUkFJTlQgImJpc25leXNfZW1wbG95bWVudHNfcGVyc29uSWRfZmtleSIgRk9SRUlHTiBLRVkgKCJwZXJzb25JZCIpIFJF",
  "RkVSRU5DRVMgImJpc25leXNfcGVvcGxlIigiaWQiKSBPTiBERUxFVEUgUkVTVFJJQ1QgT04gVVBEQVRFIENBU0NBREU7CgpBTFRFUiBUQUJMRSAiYmlzbmV5",
  "c19lbXBsb3ltZW50cyIgQUREIENPTlNUUkFJTlQgImJpc25leXNfZW1wbG95bWVudHNfY29tcGFueUlkX2ZrZXkiIEZPUkVJR04gS0VZICgiY29tcGFueUlk",
  "IikgUkVGRVJFTkNFUyAiYmlzbmV5c19jb21wYW5pZXMiKCJpZCIpIE9OIERFTEVURSBTRVQgTlVMTCBPTiBVUERBVEUgQ0FTQ0FERTsK",
].join("");

export async function POST(req: NextRequest) {
  const expected = process.env.BISNEYS_BOOTSTRAP_TOKEN;
  const provided = req.headers.get("x-bootstrap-token") ?? new URL(req.url).searchParams.get("token");
  if (!expected || provided !== expected) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const ddl = Buffer.from(DDL_B64, "base64").toString("utf8");
  const stmts = ddl.split(";").map((s) => s.trim()).filter(Boolean);
  let created = 0, skipped = 0;
  const errors: string[] = [];
  for (const s of stmts) {
    try { await db.$executeRawUnsafe(s); created++; }
    catch (e) {
      const m = (e as Error).message;
      if (/already exists|duplicate column|duplicate/i.test(m)) skipped++;
      else errors.push(m.slice(0, 160));
    }
  }
  return NextResponse.json({ ok: errors.length === 0, created, skipped, errors: errors.slice(0, 10) });
}
